---
- name: Clone gist, clearpast
  git:
    repo: https://gist.github.com/1d722e0b177fa86ecd5782c5ec132e5f.git
    dest: /tmp/clearpast

- name: Copy clearpast to PATH
  copy:
    src: /tmp/clearpast/clearpast
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0750

- name: Clone gist, sysbackup
  git:
    repo: https://gist.github.com/478c667e6ad69244f173c6e6ae583851.git
    dest: /tmp/sysbackup

- name: Copy sysbackup to PATH
  copy:
    src: /tmp/sysbackup/sysbackup
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0750
