---
- name: Clone gist, clearpast
  git:
    repo: https://gist.github.com/69983bc22086772135d3b73872ead567.git
    dest: /tmp/clearpast

- name: Copy clearpast to PATH
  copy:
    src: /tmp/clearpast/clearpast
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0750

- name: Clone gist, cleanupgrade
  git:
    repo: https://gist.github.com/42fdfb14e0bf6eb06c2f64f75a25eba6.git
    dest: /tmp/cleanupgrade

- name: Copy cleanupgrade to PATH
  copy:
    src: /tmp/cleanupgrade/cleanupgrade
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0750

- name: Clone gist, sysbackup
  git:
    repo: https://gist.github.com/17e62ce440d5cc91b0a1dd82a2d60ae7.git
    dest: /tmp/sysbackup

- name: Copy sysbackup to PATH
  copy:
    src: /tmp/sysbackup/sysbackup
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0750
